################################################################
#  Documented with reference to Leinecker's Color App example  #
################################################################

openapi: 3.0.0

info:
    description: A Simple Contact Manager's API Documentation
    version: 1.0.0
    title: A Simple Contact Manager
    contact:
        email: 'joeyhodson@knights.ucf.edu'
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
    # The two login apis likely need some sort of authentication
    # embedded in definitions below
    /login/login.php:
        post:
            tags:
                - Users
            summary: Logs user into contact manager
            operationId: userLogin
            description: Logs user into contact manager
            consumes:
                - application/json
            produces:
                - application/json
            parameters:
                username:
                    in: query
                    type: string
                password:
                    in: query
                    type: string
            schema:
                type: string
                responses:
                    200:
                        desciption: OK
                    401:
                        $ref: '#/components/responses/UnauthorizedError'
                    404:
                        description: URL Not Found
    /login/registerUser.php:
        post:
            tags:
                - Users
            summary: Creates new user and registers them in the application
            operationId: registerUser
            description: Adds a user to the manager's database
            consumes:
                - application/json
            produces:
                - application/json
            parameters:
                username:
                    in: query
                    type: string
                password:
                    in: query
                    type: string
                responses:
                    200:
                        desciption: OK
                    404:
                        description: URL Not Found
    /contacts/createContact.php:
        post:
            security:
                - bearerAuth: []
            tags:
                - Contact
            summary: Adds a contact
            operationId: createContact
            description: Adds a contact to the manager's database
            consumes:
                - application/json
            produces:
                - application/json
            parameters:
                - in: body
                name: contactObject
                description: Add Contact
                schema:
                    $ref: '#definitions/Contact'
            responses:
                200:
                    description: OK
                401:
                    $ref: '#/components/responses/UnauthorizedError'
                404:
                    description: URL Not Found
    # rework editContact
    /contacts/editContact.php:
        post:
            security:
                - bearerAuth: []
            tags:
                - Search
            summary: Edits a contact
            operationId: searchContact
            description: Searches for contact within the manager's database
            consumes:
                - application/json
            produces:
                - application/json
            parameters:
                - in: body
                name: searchObject
                description: Contact Search
                schema:
                    $ref: '#/definitions/Search'
            responses:
                200:
                    description: OK
                401:
                    $ref: '#/components/responses/UnauthorizedError'
                404:
                    description: URL Not Found
        put:
            # ^ may be required rather than post ^
    # rework removeContact
    /contacts/removeContact.php:
        post:
            security:
                - bearerAuth: []
            tags:
                - Search
            summary: Searches contacts
            operationId: searchContact
            description: Searches for contact within the manager's database
            consumes:
                - application/json
            produces:
                - application/json
            parameters:
                - in: body
                name: searchObject
                description: Contact Search
                schema:
                    $ref: '#/definitions/Search'
            responses:
                200:
                    description: OK
                401:
                    $ref: '#/components/responses/UnauthorizedError'
                404:
                    description: URL Not Found
    /contacts/searchContact.php:
        post:
            security:
                - bearerAuth: []
            tags:
                - Search
            summary: Searches contacts
            operationId: searchContact
            description: Searches for contact within the manager's database
            consumes:
                - application/json
            produces:
                - application/json
            parameters:
                - in: body
                name: searchObject
                description: Contact Search
                schema:
                    $ref: '#/definitions/Search'
            responses:
                200:
                    description: OK
                401:
                    $ref: '#/components/responses/UnauthorizedError'
                404:
                    description: URL Not Found
        get:
        # ^ likely needs a get as well / 'in: query' may be preferred ^

definitions:
    Contact:
    type: object
    required:
    - firstName
    # - lastName
    - userID
    - dateCreated
    - id
    properties:
      firstName:
        type: string
        example: John
      lastName:
        type: string
        example: Doe
      phoneNumber:
        type: string
        example: 123-456-7890
      email:
        type: string
        example: you@mail.com
      dateCreated:
        type: string
        format: date-time
        example: '2016-08-29T09:12:33.001Z'
      userID:
        description: ID of owner/user
        type: integer
        example: 1
      id:
        description: Unique identifier for this contact
        type: integer
        example: 1
  User:
    type: object
    required:
      - username
      - userID
      - password
    properties:
      username:
        type: string
        example: username123
      userID:
        type: integer
        example: 1
      password:
        type: string
        example: 9dfgs687sd

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
    responses:
        UnauthorizedError:
            description: Access token is missing or invalid

host: http://cop4331-2023.xyz/
basePath: /service
schemes:
    - https