@startuml

object Contact {
    Contact ID
    First Name
    Last Name
    Phone Number
    Email Address
}

object User {
    User ID
    Username
    Password
}

object Token {
    User ID
    Issued At Time
    Not Valid Before Time
    Expiration Time
    Issuer
    Audience
}

User --> Contact : Searches
Token --> User : Identifies
User o-- Contact
User o-- Token

@enduml