@startuml

object Contact {
    Contact ID
    Name
    Phone Number
    Email Address
}

object User {
    User ID
    Username
    Password
}

object Token {
    User ID
}

User --> Contact : Searches
User o-- Contact
User o-- Token

@enduml